import { ReactNode } from 'react'
import './globals.css'
import type { Metadata } from 'next'
import { Chat, SideBar, Userlist } from '@/components'

export const metadata: Metadata = {
  title: 'Chatbot Zebra',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        <SideBar>
          <Userlist />
          {children}
        </SideBar>
      </body>
    </html>
  )
}
